//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    
    public partial class Aula
    {
        public Aula()
        {
            this.Curso = new HashSet<Curso>();
        }
    
        public int id_aula { get; set; }
        public string nombre { get; set; }
        public Nullable<System.DateTime> fecha_alta { get; set; }
        public Nullable<int> usuario_alta { get; set; }
        public Nullable<System.DateTime> fecha_baja { get; set; }
        public Nullable<int> usuario_baja { get; set; }
        public Nullable<bool> habilitado { get; set; }
        public Nullable<int> capacidad_alumnos { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> id_colegio { get; set; }
    
        public virtual Colegio Colegio { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
        public virtual ICollection<Curso> Curso { get; set; }
    }
}
