//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    
    public partial class Barrio
    {
        public Barrio()
        {
            this.Colegio = new HashSet<Colegio>();
            this.Usuario = new HashSet<Usuario>();
        }
    
        public int id { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> id_localidad { get; set; }
    
        public virtual Localidad Localidad { get; set; }
        public virtual ICollection<Colegio> Colegio { get; set; }
        public virtual ICollection<Usuario> Usuario { get; set; }
    }
}
