//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    
    public partial class Codigo_Colegio
    {
        public int id_colegio { get; set; }
        public int id_rol { get; set; }
        public string codigo { get; set; }
        public Nullable<bool> habilitado { get; set; }
    
        public virtual Colegio Colegio { get; set; }
        public virtual Rol Rol { get; set; }
    }
}
