//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    
    public partial class Colegio
    {
        public Colegio()
        {
            this.Aula = new HashSet<Aula>();
            this.Colegio_Usuario = new HashSet<Colegio_Usuario>();
            this.Contacto_Colegio = new HashSet<Contacto_Colegio>();
            this.Reunion = new HashSet<Reunion>();
            this.Turno = new HashSet<Turno>();
            this.Codigo_Colegio = new HashSet<Codigo_Colegio>();
        }
    
        public int id_colegio { get; set; }
        public string nombre { get; set; }
        public string calle { get; set; }
        public string calle_nro { get; set; }
        public Nullable<int> id_barrio { get; set; }
        public Nullable<int> id_localidad { get; set; }
        public Nullable<int> id_provincia { get; set; }
        public Nullable<int> id_pais { get; set; }
        public Nullable<int> id_plan { get; set; }
        public Nullable<System.DateTime> fecha_suscripcion { get; set; }
        public Nullable<bool> habilitado { get; set; }
        public Nullable<System.DateTime> fecha_alta { get; set; }
        public Nullable<int> usuario_alta { get; set; }
        public Nullable<System.DateTime> fecha_baja { get; set; }
        public Nullable<int> usuario_baja { get; set; }
    
        public virtual ICollection<Aula> Aula { get; set; }
        public virtual Plan Plan { get; set; }
        public virtual ICollection<Colegio_Usuario> Colegio_Usuario { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
        public virtual ICollection<Contacto_Colegio> Contacto_Colegio { get; set; }
        public virtual ICollection<Reunion> Reunion { get; set; }
        public virtual ICollection<Turno> Turno { get; set; }
        public virtual Barrio Barrio { get; set; }
        public virtual Localidad Localidad { get; set; }
        public virtual Pais Pais { get; set; }
        public virtual Provincia Provincia { get; set; }
        public virtual ICollection<Codigo_Colegio> Codigo_Colegio { get; set; }
    }
}
