//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Curso
    {
        public Curso()
        {
            this.Alumno_Curso = new HashSet<Alumno_Curso>();
            this.Asistencia = new HashSet<Asistencia>();
            this.Examen = new HashSet<Examen>();
            this.Materia_Curso = new HashSet<Materia_Curso>();
        }
    
        public int id_curso { get; set; }
        public Nullable<int> id_aula { get; set; }
        public Nullable<int> id_profesor { get; set; }
        public Nullable<int> año { get; set; }
        public Nullable<int> id_turno { get; set; }
        public string descripcion { get; set; }
        public Nullable<System.DateTime> fecha_alta { get; set; }
        public Nullable<int> usuario_alta { get; set; }
        public Nullable<System.DateTime> fecha_baja { get; set; }
        public Nullable<int> usuario_baja { get; set; }
        public Nullable<int> nivel { get; set; }
        public Nullable<int> id_preceptor { get; set; }
    
        public virtual ICollection<Alumno_Curso> Alumno_Curso { get; set; }
        public virtual ICollection<Asistencia> Asistencia { get; set; }
        public virtual Aula Aula { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Turno Turno { get; set; }
        public virtual Usuario Usuario1 { get; set; }
        public virtual Usuario Usuario2 { get; set; }
        public virtual Usuario Usuario3 { get; set; }
        public virtual ICollection<Examen> Examen { get; set; }
        public virtual ICollection<Materia_Curso> Materia_Curso { get; set; }
    }
}
