//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    
    public partial class Materia
    {
        public Materia()
        {
            this.Examen = new HashSet<Examen>();
            this.Materia_Curso = new HashSet<Materia_Curso>();
            this.Temario = new HashSet<Temario>();
        }
    
        public int id_materia { get; set; }
        public Nullable<int> id_colegio { get; set; }
        public string descripcion { get; set; }
        public Nullable<System.DateTime> fecha_alta { get; set; }
        public Nullable<int> usuario_alta { get; set; }
        public Nullable<System.DateTime> fecha_baja { get; set; }
        public Nullable<int> usuario_baja { get; set; }
        public Nullable<int> nivel { get; set; }
    
        public virtual ICollection<Examen> Examen { get; set; }
        public virtual ICollection<Materia_Curso> Materia_Curso { get; set; }
        public virtual ICollection<Temario> Temario { get; set; }
    }
}
