//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    
    public partial class Pagina
    {
        public Pagina()
        {
            this.Rol = new HashSet<Rol>();
        }
    
        public int id_pagina { get; set; }
        public string nombre { get; set; }
        public string menu { get; set; }
        public string controlador { get; set; }
        public string accion { get; set; }
        public Nullable<int> orden { get; set; }
        public string icono { get; set; }
    
        public virtual ICollection<Rol> Rol { get; set; }
    }
}
