//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    
    public partial class Rol
    {
        public Rol()
        {
            this.Rol_Usuario = new HashSet<Rol_Usuario>();
            this.Pagina = new HashSet<Pagina>();
            this.Codigo_Colegio = new HashSet<Codigo_Colegio>();
        }
    
        public int id_rol { get; set; }
        public string descripcion { get; set; }
    
        public virtual ICollection<Rol_Usuario> Rol_Usuario { get; set; }
        public virtual ICollection<Pagina> Pagina { get; set; }
        public virtual ICollection<Codigo_Colegio> Codigo_Colegio { get; set; }
    }
}
