//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    
    public partial class Temario
    {
        public Temario()
        {
            this.Tema_Examen = new HashSet<Tema_Examen>();
        }
    
        public int id_tema { get; set; }
        public Nullable<int> id_materia { get; set; }
        public Nullable<int> año { get; set; }
        public string descripcion { get; set; }
        public string observaciones { get; set; }
        public Nullable<System.DateTime> fecha_alta { get; set; }
        public Nullable<int> usuario_alta { get; set; }
        public Nullable<System.DateTime> fecha_baja { get; set; }
        public Nullable<int> usuario_baja { get; set; }
        public Nullable<int> id_estado { get; set; }
    
        public virtual Estado_Temario Estado_Temario { get; set; }
        public virtual Materia Materia { get; set; }
        public virtual ICollection<Tema_Examen> Tema_Examen { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
    }
}
